### PR TITLE
Fix both imageviewers on X.org with DefaultDepth 30

### LINKED ISSUE #51: example/{imageviewer,sdl-imageviewer} don't work/work wrong with DefaultDepth 30
System: Arch Linux, X11 with DefaultDepth 30
Tested on various PNG images.

sdl-imageviewer always crashes, because `SDL_GetWindowSurface()` returns NULL.

imageviewer garbles the images it manages to display in the following way:
image

On slightly larger images, it crashes on `xcb_wait_for_event()` returning NULL.

### PR DESCRIPTION
**Pull request by pjanx**
Fixes #51.

### CODE REVIEW

**Comment by pjanx** [comment]
@googlebot I signed it!

**Comment by nigeltao** [comment]
Thanks!

I have some minor quibbles, but I'll fix them in follow-up commits.

**Comment by nigeltao** [comment]
Having example/imageviewer use xrender means that it was now straightforward to add a zoom/magnify feature.

I also made some other tweaks. Let me know if I broke anything on DefaultDepth 30.

**Comment by pjanx** [comment]
I totally missed the _build-example.sh_ script, or forgot about it at some point.

Indeed. Good gardening work, still working. You may simulate the situation by setting RGB24 on the root window (which is a particularly annoying change).

**Pull request merged**
